<?php

namespace ZIMZIM\CategoryProductBundle\Model\ItemHome;

use APY\DataGridBundle\Grid\Source\Entity;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use Gedmo\Sortable\Entity\Repository\SortableRepository;
use ZIMZIM\ToolsBundle\Model\APYDataGrid\ApyDataGridRepositoryInterface;
use Symfony\Component\Security\Core\SecurityContext;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class ItemHomeRepository extends SortableRepository implements ApyDataGridRepositoryInterface
{
    public function getList(Entity $source, SecurityContext $securityContext)
    {
        $tableAlias = $source->getTableAlias();
        $source->manipulateQuery(
            function (QueryBuilder $query) use ($tableAlias)
            {
                $query->addOrderBy($tableAlias . '.position', 'ASC');
            }
        );
        $source->addHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
        return $source;
    }


    public function findSortable(){

        $query = $this->createQueryBuilder('i');
        $query->addOrderBy('position', 'ASC')
                ->addHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
        return $query->getQuery()->getResult();

    }
}
