<?php

namespace ZIMZIM\CategoryProductBundle\Model;

use APY\DataGridBundle\Grid\Source\Entity;
use Doctrine\ORM\Query;
use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class ItemHomeRepository extends SortableRepository implements ApyDataGridRepositoryInterface
{
    public function getList(Entity $source)
    {
        $source->addHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
        return $source;
    }
}
