<?php

namespace ZIMZIM\CategoryProductBundle\Model;

use Doctrine\ORM\Query;
use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class ItemHomeRepository extends SortableRepository implements ApyDataGridRepositoryInterface
{
    public function getList($source)
    {


        return $source;
    }
}
