zimzim_categoryproduct_itemhome:
    resource: "@ZIMZIMCategoryProductBundle/Resources/config/routing/itemhome.yml"
    prefix:   /

zimzim_categoryproduct_admincategory:
    resource: "@ZIMZIMCategoryProductBundle/Resources/config/routing/admincategory.yml"
    prefix:   /zimzim/category/

zimzim_categoryproduct_category:
    resource: "@ZIMZIMCategoryProductBundle/Resources/config/routing/category.yml"
    prefix:   /category/

zimzim_categoryproduct_adminproduct:
    resource: "@ZIMZIMCategoryProductBundle/Resources/config/routing/adminproduct.yml"
    prefix:   /zimzim/product/

zimzim_categoryproduct_product:
    resource: "@ZIMZIMCategoryProductBundle/Resources/config/routing/product.yml"
    prefix:   /product/

zimzim_categoryproduct_adminitemhome:
    resource: "@ZIMZIMCategoryProductBundle/Resources/config/routing/adminitemhome.yml"
    prefix:   /zimzim/itemhome/
