<?php

namespace ZIMZIM\CategoryProductBundle\Model\CategoryProduct;

use APY\DataGridBundle\Grid\Source\Entity;
use Doctrine\ORM\Query;
use Doctrine\ORM\EntityRepository;
use ZIMZIM\ToolsBundle\Model\APYDataGrid\ApyDataGridRepositoryInterface;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class ProductRepository extends EntityRepository implements ApyDataGridRepositoryInterface
{
    public function getList(Entity $source)
    {
        $source->addHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

        return $source;
    }

    public function getByCategory($category)
    {

        $query = $this->createQueryBuilder('p');
        $query->join('p.categoryproducts', 'cp')
            ->where('cp.category = :category')
            ->setParameter('category', $category)
            ->orderBy('cp.position', 'ASC');

        $query->getQuery()->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );

        return $query->getQuery()->getResult();
    }
}
