services:
    zimzim_categoryproduct_configuration_category:
        class: "ZIMZIM\CategoryProductBundle\Doctrine\Configuration\ConfigurationCategory"
        arguments:
            - @zimzim_category_product.entity.category
            - %zimzim_category_product.category_form%

    zimzim_categoryproduct_configuration_categoryproduct:
        class: "ZIMZIM\CategoryProductBundle\Doctrine\Configuration\ConfigurationCategoryProduct"
        arguments:
            - @zimzim_category_product.entity.categoryproduct
            - %zimzim_category_product.categoryproduct_form%

    zimzim_categoryproduct_configuration_product:
        class: "ZIMZIM\CategoryProductBundle\Doctrine\Configuration\ConfigurationProduct"
        arguments:
            - @zimzim_category_product.entity.product
            - %zimzim_category_product.product_form%

    zimzim_categoryproduct_configuration_itemhome:
        class: "ZIMZIM\CategoryProductBundle\Doctrine\Configuration\ConfigurationItemHome"
        arguments:
            - %zimzim_category_product.itemhome_class%
            - %zimzim_category_product.itemhome_form%
