services:
    zimzim_categoryproduct_factory_itemhome:
        class: "ZIMZIM\CategoryProductBundle\Factory\ItemHomeFactory"
        arguments:
            - %zimzim_category_product.itemhome_data.category_class%
            - %zimzim_category_product.itemhome_data.product_class%
            - %zimzim_category_product.itemhome_data.category_form%
            - %zimzim_category_product.itemhome_data.product_form%