services:
    zimzim_categoryproduct_factory_itemhome:
        class: "ZIMZIM\CategoryProductBundle\Factory\ItemHomeFactory"
        arguments:
            - @zimzim_category_product.entity.itemhomecategory
            - @zimzim_category_product.entity.itemhomeproduct
            - %zimzim_category_product.itemhome_data.category_form%
            - %zimzim_category_product.itemhome_data.product_form%
