services:

    zimzim_categoryproduct_categorymanager:
        class: "ZIMZIM\CategoryProductBundle\Doctrine\CategoryManager"
        arguments:
            - @doctrine.orm.entity_manager
            - @zimzim_categoryproduct_configuration_category

    zimzim_categoryproduct_categoryproductmanager:
        class: "ZIMZIM\CategoryProductBundle\Doctrine\CategoryProductManager"
        arguments:
            - @doctrine.orm.entity_manager
            - @zimzim_categoryproduct_configuration_categoryproduct

    zimzim_categoryproduct_productmanager:
        class: ZIMZIM\CategoryProductBundle\Doctrine\ProductManager
        arguments:
            - @doctrine.orm.entity_manager
            - @zimzim_categoryproduct_configuration_product

    zimzim_categoryproduct_itemhomemanager:
        class: ZIMZIM\CategoryProductBundle\Doctrine\ItemHomeManager
        arguments:
            - @doctrine.orm.entity_manager
            - @zimzim_categoryproduct_configuration_itemhome
            - @zimzim_categoryproduct_factory_itemhome