zimzim_categoryproduct_product_showbyslug:
    path:     /{slug}/
    defaults: { _controller: "ZIMZIMCategoryProductBundle:Product:showproductbyslug" }
    requirements:
        _method:  GET
        slugproduct: "[0-9a-z-_]+"
